### ISSUE TITLE
Issue with CircleCI

### ISSUE THREAD

**Issue by ammaratef45** [adamantium-architects/docker-flutter#1]
Hello, Thanks for the great image

I have a problem running it in CircleCI

Is it possible that you solve it?

>CircleCI was unable to start the container because of a userns remapping failure in Docker.
This typically means the image contains files with UID/GID values that are higher than Docker and CircleCI can use.
Checkout our docs https://circleci.com/docs/2.0/high-uid-error/ to learn how to fix this problem.
Original error: CircleCI was unable to start the container because of a userns remapping failure in Docker.
This typically means the image contains files with UID/GID values that are higher than Docker and CircleCI can use.
Checkout our docs https://circleci.com/docs/2.0/high-uid-error/ to learn how to fix this problem.
Original error: failed to register layer: Error processing tar file(exit status 1): Container ID 397546 cannot be mapped to a host ID

**Comment by jmcpeek** [comment]
@ammaratef45 I'll take a look and see if I can fix it for you!

**Comment by ammaratef45** [comment]
@jmcpeek Thank you 😄

**Comment by jmcpeek** [comment]
@ammaratef45 Can you try either `dev` or `latest` tagged docker image and see if that resolves your issue?

**Comment by ammaratef45** [comment]
With dev the output was
>CircleCI was unable to start the container because of a userns remapping failure in Docker.
This typically means the image contains files with UID/GID values that are higher than Docker and CircleCI can use.
Checkout our docs https://circleci.com/docs/2.0/high-uid-error/ to learn how to fix this problem.
Original error: CircleCI was unable to start the container because of a userns remapping failure in Docker.
This typically means the image contains files with UID/GID values that are higher than Docker and CircleCI can use.
Checkout our docs https://circleci.com/docs/2.0/high-uid-error/ to learn how to fix this problem.
Original error: failed to register layer: Error processing tar file(exit status 1): Container ID 397546 cannot be mapped to a host ID

With latest the output was
>CircleCI was unable to start the container because of a userns remapping failure in Docker.
This typically means the image contains files with UID/GID values that are higher than Docker and CircleCI can use.
Checkout our docs https://circleci.com/docs/2.0/high-uid-error/ to learn how to fix this problem.
Original error: CircleCI was unable to start the container because of a userns remapping failure in Docker.
This typically means the image contains files with UID/GID values that are higher than Docker and CircleCI can use.
Checkout our docs https://circleci.com/docs/2.0/high-uid-error/ to learn how to fix this problem.
Original error: failed to register layer: Error processing tar file(exit status 1): Container ID 397546 cannot be mapped to a host ID

**Comment by ammaratef45** [comment]
@jmcpeek The same error with the beta tag too

**Comment by jmcpeek** [comment]
@ammaratef45 Walking through the created image, it appears to be bad metadata (file ownership) on the gradle wrapper downloaded by `flutter doctor`.

I have added an ownership change **after** running `flutter doctor` to correct this issue as well as the potential of it happening again.

Please confirm if this resolves your issue.

**Comment by ammaratef45** [comment]
@jmcpeek I'm really sorry
Your change solved the problem (I just was using the beta tag)
Thank you very much

**Comment by jmcpeek** [comment]
@ammaratef45 Glad it resolved the issue. All tags should be resolved - looks like you just happened to check before the images had finished being built on Docker Hub.

Thanks for confirming!
