### ISSUE TITLE
Not an issue - how or where to use?

### ISSUE THREAD

**Issue by carlosen14** [adamantium-architects/docker-flutter#2]
How is this image used? I'm still a begginer in flutter looking for containers related to it.

is this image to compile the project inside a container for CI/CD?

Thanks.

**Comment by jmcpeek** [comment]
Using it to build your application and run its tests in a CI/CD pipeline would be one of the primary uses.

You could also generate the associated APK to make both internal or public releases.

You could also use it for configured build environment for your development workstation/setup directly, though this is less valuable, as the flutter SDK has built-in update features.
